name: Publish to NPM on Master Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install NPM packages
      run: npm install
    - name: Run the tests
      run: npm test
    - name: Build the project
      run: npm run-script build
    - name: Publish the project
      run: npm publish
